import type { MetadataRoute } from "next";

const BASE = "https://www.relentcarehospitals.com";

const routes = [
  "/",
  "/dr-salison-salim-best-ent-doctor-thrissur",
  "/dr-aiswarya-thambi-best-pulmonologist-thrissur",
  "/dr-vidya-ramdas-ent-surgeon-thrissur-top",
  "/best-ent-services-thrissur",
  "/ear-surgeries-best-ent-doctors-thrissur",
  "/hearing-loss-treatment",
  "/hearing-tests-hearing-aids-thrissur",
  "/tinnitus-causes-treatment-thrissur",
  "/wax-removal-thrissur-ent-surgeon",
  "/chronic-otitis-media-facial-nerve-palsy-thrissur",
  "/otitis-externa-or-swimmers-ear",
  "/mastoiditis-thrissur-relentcare-ent-centre",
  "/vertigo-treatment-thrissur",
  "/menieres-disease",
  "/acoustic-neuroma-diagnosis-and-treatment",
  "/tympanoplasty-eardrum-surgery-endoscopic",
  "/preauricular-sinus-surgery",
  "/pseudocyst-pinna-thrissur-best-treatment",
  "/rhinology-sinus-surgeries",
  "/functional-endoscopic-sinus-surgery-thrissur-ent-surgeon",
  "/deviated-nasal-septum-surgery-best-doctor-thrissur",
  "/endoscopic-turbinoplasty-surgery-thrissur-kerala",
  "/nasal-polyp-treatment-thrissur-best-ent-centre",
  "/antrochoanal-polyp-kerala-thrissur-nose",
  "/septoplasty-thrissur",
  "/sluders-neuralgia",
  "/foreign-body-nose-and-airway-thrissur-kerala",
  "/laryngology-services",
  "/leukoplakia-causes-treatment-ent-doctor",
  "/muscle-tension-dysphonia",
  "/hoarsness",
  "/vocal-nodules-laryngologist-thrissur",
  "/vocal-sulcus-thrissur-ent-doctor",
  "/chronic-laryngitis",
  "/laryngo-pharyngeal-reflux-disease-lprd",
  "/foreign-body-throat-and-oesophagus",
  "/globus-sensation-throat",
  "/adenotonsillectomy-in-adult",
  "/adenotonsillectomy",
  "/hearing-loss-in-children-treatment-thrissur-pediatric-ent",
  "/nose-bleed-children-thrissur-ent",
  "/pediatric-nasal-obstruction",
  "/pediatric-sleep-apnoea",
  "/osa-surgery",
  "/chronic-ear-infection",
  "/tonsillitis",
  "/mumps-symptoms-and-treatment-thrissur-kerala-india",
  "/insomnia-sleep-disorder-thrissur",
  "/sleepiness",
  "/sleep-apnoea-snoring-best-doctor-india-thrissur",
  "/restless-leg-syndrome",
  "/allergy-test-skin-prick-test",
  "/asthma-and-allergy",
  "/allergy-and-immunotherapy",
  "/chronic-cough",
  "/respiratory-disease",
  "/snoring-with-osa-and-its-treatement",
  "/chronic-obstructive-sleep-apnoea",
  "/bronchoscopy",
  "/allergy-clinic",
  "/migraine-treatment-thrissur-best-in-kerala",
  "/headache-cause-treatment",
  "/best-facial-aesthetic-services",
  "/acne-treatment-thrissur-kerala",
  "/best-laser-treatment-thrissur",
  "/deep-acne-scar-subcision-thrissur",
  "/best-glutathione-iv-thrissur",
  "/best-prp-therapy-thrissur",
  "/lipoma",
  "/nose-pierceing-thrissur-doctor",
  "/ear-piercing-services",
  "/ear-lobule-repair-best-thrissur-doctor",
  "/wart-removal-thrissur",
  "/home-visit-service-thrissur",
  "/blog",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${BASE}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "/" ? "weekly" : "monthly",
    priority: route === "/" ? 1 : route.length < 30 ? 0.8 : 0.6,
  }));
}
